# -*- coding: utf-8 -*-
"""customer segmentation Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkMcFXzNQR9sRVPWbmluO7wp9bDWVzM4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings("ignore")
# Load dataset
df = pd.read_csv("data.csv", encoding="latin1")
# Basics Information
print(" EDA")
print(df.head())
print(df.shape)
print(df.info())
print(df.isnull().sum())
# Dataset Overview
print(df.describe())
# Data cleaning & preprocessing
print("Data cleaning and preprocessong")
df = df.dropna(subset=["CustomerID"])
df = df[df["Quantity"] > 0]
df = df[df["UnitPrice"] > 0]
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["CustomerID"] = df["CustomerID"].astype(str)
# Feature Engineering
print("Feature Engineering")
df["TotalAmount"] = df["Quantity"] * df["UnitPrice"]
df["Month"] = df["InvoiceDate"].dt.month
df["Year"] = df["InvoiceDate"].dt.year
df["Day"] = df["InvoiceDate"].dt.day_name()
df["Hour"] = df["InvoiceDate"].dt.hour
# Top Countries
top_countries = (df.groupby("Country")["TotalAmount"].sum().sort_values(ascending=False).head(10))
plt.figure(figsize=(12,6))
sns.barplot(
    x=top_countries.values,
    y=top_countries.index)
plt.title("Top Countries by Revenue")
plt.xlabel("Revenue")
plt.ylabel("Country")
plt.show()
# Top Products
top_products = (df.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(10))
plt.figure(figsize=(12,6))
sns.barplot(x=top_products.values,
            y=top_products.index)
plt.title("Top Selling Products")
plt.xlabel("Quantity Sold")
plt.ylabel("Products")
plt.show()
# Monthly Sales Trend
monthly_sales = (df.groupby("Month")["TotalAmount"].sum()
)
plt.figure(figsize=(10,5))
monthly_sales.plot(marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.grid()
plt.show()
# Correlation Heatmap
numeric_df = df.select_dtypes(include=np.number)
plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(),annot=True,cmap="coolwarm"
)
plt.title("Correlation Heatmap")
plt.show()
print("Customer segmentation Analysis")
# RFM Analysis
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)
rfm = df.groupby("CustomerID").agg({
    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
    "InvoiceNo": "nunique",
    "TotalAmount": "sum",
    "Quantity": "sum"
})
rfm.columns = ["Recency","Frequency","Monetary","Quantity"]
#  customer Features
avg_order_value = (df.groupby("CustomerID")["TotalAmount"].mean())
unique_products = (df.groupby("CustomerID")["StockCode"].nunique()
)
country_count = ( df.groupby("CustomerID")["Country"].nunique())
rfm["AvgOrderValue"] = avg_order_value
rfm["UniqueProducts"] = unique_products
rfm["CountryCount"] = country_count
# Missing Value Check
print(rfm.isnull().sum())
# Outlier Detection
iso = IsolationForest(contamination=0.02,random_state=42)
outliers = iso.fit_predict(rfm)
rfm = rfm[outliers == 1]
# Scaling
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm)
# Elbow Method
wcss = []
for i in range(2, 11):
    kmeans = KMeans(n_clusters=i,random_state=42,n_init=10)
    kmeans.fit(rfm_scaled)
    wcss.append(kmeans.inertia_)
plt.figure(figsize=(8,5))
plt.plot(range(2,11),wcss,marker="o")
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid()
plt.show()
# Silhouette Scores
scores = []
for i in range(2, 11):
    model = KMeans(n_clusters=i,random_state=42,n_init=10)
    labels = model.fit_predict(rfm_scaled)
    score = silhouette_score(rfm_scaled,labels)
    scores.append(score)
plt.figure(figsize=(8,5))
plt.plot(range(2,11),scores,marker="o")
plt.title("Silhouette Scores")
plt.xlabel("Clusters")
plt.ylabel("Score")
plt.grid()
plt.show()
# Final Model
kmeans = KMeans(n_clusters=4,random_state=42,n_init=10)
rfm["Cluster"] = kmeans.fit_predict(rfm_scaled)
# Cluster Summary
cluster_summary = rfm.groupby("Cluster").mean()
print(cluster_summary)
# Cluster Counts
print(rfm["Cluster"].value_counts())
# PCA Visualization
pca = PCA(n_components=2)
pca_data = pca.fit_transform(rfm_scaled)
rfm["PCA1"] = pca_data[:,0]
rfm["PCA2"] = pca_data[:,1]
plt.figure(figsize=(12,7))
sns.scatterplot( x="PCA1", y="PCA2", hue="Cluster", palette="Set1", data=rfm, s=100)
plt.title("Customer Segmentation using K-Means")
plt.show()
# Cluster Distribution
plt.figure(figsize=(8,5))
sns.countplot( x="Cluster", data=rfm)
plt.title("Cluster Distribution")
plt.show()
# Pairplot
sns.pairplot(rfm,hue="Cluster",vars=["Recency","Frequency","Monetary"])
plt.show()
# Customer Segment Labels
segment_map = {
    0: "Loyal Customers",
    1: "High Value Customers",
    2: "Regular Customers",
    3: "Inactive Customers"
}
rfm["Segment"] = rfm["Cluster"].map(segment_map)
# Final Segmentation Table
print( rfm[["Recency","Frequency","Monetary","Segment"]].head())
# Export Final Output
rfm.to_csv("customer_segments.csv")
print("Customer Segmentation Completed")